/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parqueo;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adriana Abad
 */
public class Entrada extends javax.swing.JFrame {

    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSalir = new javax.swing.JButton();
        jRetirar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jIngresar = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(459, 669));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSalir.setForeground(new java.awt.Color(0, 0, 0));
        jSalir.setText("Exit");
        jSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 130, 50));

        jRetirar.setForeground(new java.awt.Color(0, 0, 0));
        jRetirar.setText("Retirar Vehiculo");
        jRetirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 140, 50));

        jBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jBuscar.setText("Buscar Vehiculo");
        jBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 130, 50));

        jIngresar.setForeground(new java.awt.Color(0, 0, 0));
        jIngresar.setText("Ingresar Vehiculo");
        jIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 130, 50));

        jlTitulo.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("Parking Abad");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Parqueo/fondo-de-pantalla-coches-9.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 459, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void jIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarActionPerformed
       
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Entrada.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Registro objventana1 = new Registro();
        objventana1.setVisible(true);
        
        
    }//GEN-LAST:event_jIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jRetirar;
    private javax.swing.JButton jSalir;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
